version: '3'
services:
  postgres-server:
    build: db
    env_file:
      - db/db.env
    volumes:
      - db-data:/var/lib/postgresql/data/
    ports: 
      - "5432:5432"
  app:
    build: .
    command: /bin/sh -c "/app/runServer.sh"
    ports:
      - "8000:8000"
    depends_on:
      - postgres-server

volumes:
  db-data: 